### PR TITLE
smaller image via multi-stage build

### PR DESCRIPTION
**Pull request by jrabbit**
You should publish the image on docker hub too!

### CODE REVIEW

**Comment by tsileo** [comment]
Hey, thanks for the PR!

Did you try to run the container locally?

I thought go binary would link dynamically to libc in some way, and thus using Alpine would cause issue.

Thanks!

**Comment by jrabbit** [comment]
Go binaries are statically linked by default and idk if they even link libc
if you don't ask. I didn't actually run it in a system though, there may be
an assumption of services somewhere (I dont claim to know how golang tls
validation works) but this seems pretty self contained.

**Comment by tsileo** [comment]
I will run it just to be sure before merging (as I've never tried a go binary compiled in another stage and running in Alpine), otherwise it looks good to me.
Thanks!

**Comment by tsileo** [comment]
There's an issue with Dockerfile, I reverted the change. I will try to investigate if I have time.

**Pull request merged**
